import { Page } from '@/components/site-shell';
import Link from 'next/link';

function PaperArt({ className = '' }: { className?: string }) { return <div className={`paper-art ${className}`} aria-hidden="true"><i></i><b></b><em></em><span></span></div>; }
function ArrowLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link className="text-link" href={href}>{children} <span aria-hidden="true">→</span></Link>; }

const impact = [
  { year: '2014', title: 'Classroom desks', text: 'The historical record describes a student-led effort that raised funds for desks made locally in Kenya.', status: 'Historical record' },
  { year: '2015', title: 'Energy goal', text: 'Existing materials describe a proposed renewable-energy project. Its completion and current status need confirmation.', status: 'Verify current status' },
  { year: '2018–', title: 'Education support', text: 'Past site content describes scholarship support. Current biographies and permissions are being reviewed.', status: 'Details to be confirmed' },
  { year: '2023', title: 'Water project', text: 'A past partnership effort included a rain-barrel auction connected to a well goal. The outcome needs current verification.', status: 'Verify current status' },
];

export function HomePage() {
  return <Page>
    <section className="home-hero"><div className="hero-inner page-width"><div className="hero-copy"><h1>Two places.<br />One ongoing<br />partnership.</h1><p>Connecting Laguna Beach students and the Oloolaimutia community through a relationship that began in 2012.</p><div className="hero-actions"><Link className="button button-sun" href="/our-story">Learn our story</Link><Link className="button button-outline" href="/get-involved">Get involved</Link></div></div><PaperArt className="hero-art" /></div></section>
    <section className="intro-band section-space"><div className="narrow intro-copy"><p className="eyebrow">A student-led partnership</p><h2>Built by students. Sustained through relationship.</h2><p>Laguna Maasai Partnership is a student-led initiative within Laguna Beach High School Model United Nations. Its purpose is to nurture a long-term connection with the Oloolaimutia community—rooted in listening, learning, fundraising, and shared priorities.</p></div></section>
    <section className="origin-section"><div className="page-width origin-grid"><div><p className="eyebrow sun">Where it began</p><h2>One visit.<br />A connection that kept going.</h2></div><div className="origin-copy"><p>In 2012, LBHS MUN advisor Jun Shen visited Oloolaimutia Elementary School in the Maasai Mara region of Kenya. What began with a conversation became the foundation for a student initiative and an ongoing partnership.</p><p className="notice">This origin story is based on historical materials and will be expanded with approved, current context.</p><ArrowLink href="/our-story">Read the full story</ArrowLink></div></div></section>
    <section className="relationship-section section-space"><div className="page-width"><p className="eyebrow">A relationship, not a one-time project</p><div className="relationship-head"><h2>Two places,<br />one relationship.</h2><p>Partnership means making space for long-term learning and communication—not assuming, speaking for others, or treating support as a one-way story.</p></div><div className="relationship-spread"><article><span className="place-motif">01</span><h3>Laguna Beach</h3><p>Students learn, organize, and keep the connection active with support from families, alumni, and the local community.</p></article><figure aria-hidden="true"></figure><article><span className="place-motif">02</span><h3>Oloolaimutia</h3><p>Community perspectives and locally informed priorities belong at the center of future updates, shared with permission and context.</p></article></div></div></section>
    <section className="impact-preview"><div className="page-width"><div className="split-heading"><div><p className="eyebrow sun">Our impact</p><h2>Accountability<br />with context.</h2></div><p>These are historical project records, not current performance claims. Each will be updated only after its source, status, and context are confirmed.</p></div><div className="impact-list">{impact.slice(0, 4).map((item) => <article key={item.title}><span>{item.year}</span><h3>{item.title}</h3><p>{item.text}</p><small>{item.status}</small></article>)}</div><ArrowLink href="/impact">Explore the project archive</ArrowLink></div></section>
    <section className="jewelry-preview"><div className="page-width jewelry-grid"><PaperArt className="jewelry-art" /><div><p className="eyebrow">Maasai jewelry</p><h2>Made with care.<br />Shared with context.</h2><p>Jewelry has been an important part of the partnership’s history. Before presenting inventory, prices, artisan stories, or purchase options, the program is confirming the details that make those pages accurate and fair.</p><ArrowLink href="/jewelry">Explore the jewelry program</ArrowLink></div></div></section>
    <SupportPanel />
  </Page>;
}

function SupportPanel() { return <section className="support-panel"><div className="page-width support-inner"><div className="support-intro"><p className="eyebrow sun">Participate</p><h2>Support the<br />partnership.</h2><p>There are many ways to help keep this relationship strong and student-led.</p></div><Link className="support-route" href="/get-involved"><strong>Get involved</strong><span>Join events, help with initiatives, and bring friends along.</span></Link><Link className="support-route" href="/get-involved#support"><strong>Stay in touch</strong><span>Reach out when the official contact route is confirmed.</span></Link><Link className="support-route" href="/get-involved#support"><strong>Support the work</strong><span>Help sustain learning, connection, and shared effort.</span></Link></div></section>; }

export function StoryPage() {
  return <Page><section className="page-hero page-hero-cream"><div className="page-width page-hero-grid"><div><p className="eyebrow">Our story</p><h1>A relationship built to last.</h1><p className="large-copy">The partnership began with a visit and grew through years of student commitment, communication, and care.</p></div><PaperArt className="page-art" /></div></section><section className="story-intro section-space"><div className="page-width story-columns"><div><p className="eyebrow">The beginning</p><h2>2012: a visit, a conversation, a new commitment.</h2></div><div><p>Historical materials say that Jun Shen, an LBHS MUN advisor, visited Oloolaimutia Elementary School in 2012. After returning to Laguna Beach, he shared what he had learned with students. They formed what became the Laguna Maasai Partnership within LBHS MUN.</p><p className="notice">This account will be reviewed with the current program and community partners before it becomes a complete public narrative.</p></div></div></section><section className="timeline-section"><div className="page-width"><p className="eyebrow sun">A living timeline</p><div className="timeline"><article><span>2012</span><h3>A visit becomes a relationship</h3><p>Historical materials document the beginning of a connection between Laguna Beach and Oloolaimutia.</p></article><article><span>2014–2023</span><h3>Students carry the work forward</h3><p>Fundraising, school-focused projects, and jewelry sales appear across the archived partnership record.</p></article><article><span>Now</span><h3>Listen, verify, continue</h3><p>The next chapter depends on current priorities, consented stories, and transparent ways to participate.</p></article></div></div></section><section className="how-section section-space"><div className="page-width"><p className="eyebrow">How the partnership works</p><h2>Learn <i>→</i> connect <i>→</i> act <i>→</i> return.</h2><div className="how-copy"><p>Students and local supporters learn about the partnership, organize around approved priorities, and stay accountable to the people and context behind the work. This is a framework for ongoing relationship—not a claim that the same model fits every moment.</p><ArrowLink href="/get-involved">Find a way to participate</ArrowLink></div></div></section></Page>;
}

export function ImpactPage() {
  return <Page><section className="page-hero page-hero-dark"><div className="page-width impact-hero-grid"><div><p className="eyebrow sun">Our impact</p><h1>Start with what we can stand behind.</h1><p className="large-copy">The project archive is a starting point. It is not a live dashboard, and historical information remains clearly marked until updated.</p></div><aside><strong>Launch principle</strong><span>Every current number, project outcome, and personal story needs a source, owner, and review date.</span></aside></div></section><section className="archive-section section-space"><div className="page-width"><div className="split-heading"><div><p className="eyebrow">Project archive</p><h2>Historical work,<br />clearly labeled.</h2></div><p>We are preserving the record while creating space for future updates that distinguish past claims from confirmed current information.</p></div><div className="archive-list">{impact.map((item) => <article key={item.title}><span>{item.year}</span><div><h3>{item.title}</h3><p>{item.text}</p></div><small>{item.status}</small></article>)}</div></div></section><section className="confirm-section"><div className="page-width confirm-grid"><div><p className="eyebrow">Current updates</p><h2>Information is being collected.</h2></div><div><p>When a current project is ready to share, this is where visitors will find its context, purpose, update date, source, and relevant images or stories with permission.</p><p className="notice">No current funding goal, project status, or outcome is being represented here yet.</p></div></div></section></Page>;
}

export function JewelryPage() {
  return <Page><section className="page-hero page-hero-clay"><div className="page-width page-hero-grid"><div><p className="eyebrow">Maasai jewelry</p><h1>Start with the makers and the meaning.</h1><p className="large-copy">The jewelry program is part of the partnership’s history. Its next public chapter will be shaped by accurate, partner-approved context.</p></div><PaperArt className="jewelry-page-art" /></div></section><section className="jewelry-story section-space"><div className="page-width story-columns"><div><p className="eyebrow">The program</p><h2>Handmade work deserves a careful introduction.</h2></div><div><p>Historical partnership materials describe handmade jewelry reaching Laguna Beach, where LBHS students offered pieces through local sales. Details about current makers, inventory, pricing, sales routes, and the flow of funds are being confirmed before publication.</p><p className="notice">The site will not advertise a catalog or make financial claims until the program approves them.</p></div></div></section><section className="jewelry-placeholder"><div className="page-width placeholder-grid"><div><p className="eyebrow sun">Coming with approval</p><h2>A gallery with real context.</h2><p>When current pieces and permissions are available, this space can share images, care notes, purchase information, and artisan stories in a way that does not reduce culture to decoration.</p></div><div className="gallery-placeholder"><span>Current imagery<br />to be approved</span></div></div></section><section className="support-panel compact"><div className="page-width support-inner"><div><p className="eyebrow sun">Stay connected</p><h2>Interested in future jewelry updates?</h2></div><div><p>Use the partnership’s approved contact route once it is confirmed. Until then, explore ways to support the student effort.</p><Link className="button button-sun" href="/get-involved">Explore ways to participate <span aria-hidden="true">→</span></Link></div></div></section></Page>;
}

const paths = [{ title: 'Support financially', text: 'Payment destination, account ownership, fees, and tax information will be shown here once confirmed.', tag: 'Support details to be confirmed' }, { title: 'Join the student effort', text: 'Information about participation through LBHS MUN will be added with current leadership and meeting details.', tag: 'Student information to be confirmed' }, { title: 'Host a fundraiser', text: 'Students, families, and community groups can organize a future event with guidance from the partnership.', tag: 'Contact route to be confirmed' }, { title: 'Learn and share', text: 'Future resources will make it easier to follow partnership updates and share accurate information.', tag: 'Updates to be confirmed' }];

export function GetInvolvedPage() {
  return <Page><section className="page-hero page-hero-green"><div className="page-width page-hero-grid"><div><p className="eyebrow sun">Get involved</p><h1>Participation starts with a clear path.</h1><p className="large-copy">Support should be transparent, respectful, and grounded in what the partnership can responsibly share.</p></div><PaperArt className="page-art" /></div></section><section className="path-section section-space"><div className="page-width"><p className="eyebrow">Choose a path</p><h2>Take part in a way that fits.</h2><div className="path-grid">{paths.map((path, index) => <article key={path.title}><span>0{index + 1}</span><h3>{path.title}</h3><p>{path.text}</p><small>{path.tag}</small></article>)}</div></div></section><section id="support" className="support-details"><div className="page-width support-details-grid"><div><p className="eyebrow sun">Support the partnership</p><h2>Clear context comes before a transaction.</h2></div><div><p>Before accepting contributions online, the partnership will publish where funds go, who is responsible for the account, available payment methods, any fees or restrictions, tax status, and what a supporter can expect next.</p><div className="contact-state"><strong>Official contact details are being confirmed.</strong><span>When the partnership’s designated contact route is ready, it will appear here.</span></div></div></div></section><section className="faq-section section-space"><div className="page-width faq-layout"><div><p className="eyebrow">Questions</p><h2>Practical answers, with current information.</h2></div><div className="faq-list"><details><summary>What is the Laguna Maasai Partnership?</summary><p>A student-led initiative within Laguna Beach High School Model United Nations, built around a long-term relationship with the Oloolaimutia community.</p></details><details><summary>Is this part of LBHS MUN?</summary><p>Yes. The partnership is a student-led initiative within Laguna Beach High School Model United Nations.</p></details><details><summary>Can I donate or buy jewelry now?</summary><p>Current support and jewelry details are under review. This site will provide only approved, transparent routes when they are ready.</p></details><details><summary>How are stories and photos approved?</summary><p>Future public stories and imagery will be published only with appropriate permission, context, and attribution.</p></details></div></div></section></Page>;
}
